global:
  scrape_interval: 15s

scrape_configs:
- job_name: node_homeserver
  static_configs:
  - targets: ['[fd33:1491:4cfa:f000::1]:9100']
- job_name: node_router
  static_configs:
  - targets: ['[fd33:1491:4cfa:100::1]:9100']
- job_name: bind
  static_configs:
  - targets: ['[fd33:1491:4cfa:100::1]:9119']

- job_name: blackbox-icmp
  scrape_interval: 1m
  metrics_path: /probe
  params:
    module: [icmp]
  static_configs:
    - targets:
      - fd33:1491:4cfa:500::1
      - 2620:fe::fe
      - 8.8.8.8
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115
